#!/bin/bash

RED='\e[1;91m'
ORANGE='\e[1;93m'
PURPLE='\e[1;95m'
BLUE='\e[1;94m'
STOP='\e[0m'

eth0=$(ip a show eth0 2>&1 | grep inet | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | head -1)
tun0=$(ip a show tun0 2>&1 | grep inet | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | head -1)

        if [ -z "$eth0" ]
        then
        echo ""
        echo -e " ${RED}ERR::${STOP}network failure detected, troubleshooting guidance at: ${RED}https://www.highspeedinternet.com/resources/no-internet-connection-troubleshooting-guide${STOP}"
        eth0="disabled"
        fi

        if [ -z "$tun0" ]
        then
        tun0="disabled"
        fi

echo ""
echo -e " - ${ORANGE}LocalHost${STOP} ip address (${PURPLE}eth0${STOP}): ${BLUE}$eth0${STOP}"
echo ""
echo -e " - ${ORANGE}VPN${STOP} ip address (${PURPLE}tun0${STOP}): ${BLUE}$tun0${STOP}"
